//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDpop : DbContext
    {
        public BDpop()
            : base("name=BDpop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Бренд> Бренд { get; set; }
        public virtual DbSet<Информация_о_косметике> Информация_о_косметике { get; set; }
        public virtual DbSet<Класификация> Класификация { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Страна> Страна { get; set; }
        public virtual DbSet<Тип_косметики> Тип_косметики { get; set; }
    }
}
